# fly.toml app configuration file generated for black-glitter-6413 on 2023-08-20T15:39:00+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-glitter-6413"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
